adminUser:
  password: vault:jx-aps-mustangflicker/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-mustangflicker:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-mustangflicker:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-mustangflicker/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-mustangflicker/prow:hmacToken
